version: '3.1'

services:

  postgres:
    container_name: postgres_container
    image: postgres
    build:
      context: ./db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tatcha
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    depends_on: 
      - postgres
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: calistamiller16@gmail.com
      PGADMIN_DEFAULT_PASSWORD: yttp
    tty: true

  # web server
  node-container:
    # build an image using the Dockerfile in the current directory
    build:
      context: ./node

    # map external port 8000 to internal port 3000
    ports:
      - 8000:3000

    # creating a volume mount is nice for development
    volumes:
      - ./server:/root/server

    # tell this container not to start until the mongo container starts
    depends_on:
      - postgres